### ISSUE TITLE
highlighing errors in Prism client logs 

### ISSUE THREAD

**Issue by Dobby-progam** [aternosorg/codex-minecraft#48]
I uploaded a log [https://mclo.gs/xm3ryYO](https://mclo.gs/xm3ryYO) 
but there is no highlighting at errors or warnings.

**Comment by JulianVennen** [comment]
Prism Launcher logs don't really have log levels.
What you actually want is that log to be detected as a quilt log.
Due to how early that crash happened, it can't be identified as a client log, but it should be detected as a quilt server log.
The reason why that wasn't the case is that we previously required the quilt log message to be the first in the log.
This is fixed by the latest release.
